name: check-secrets-action
author: mattdavis0351
description: validation action for this lab

inputs:
  MI_SECRETO:
    description: $MI_SECRETO
    required: true
  secrets-context:
    description: The GitHub Actions secrets context object
    required: true

runs:
  using: node12
  main: "dist/index.js"
